### ISSUE TITLE
play.ws.ssl.loose.acceptAnyCertificate=true

### ISSUE THREAD

**Issue by aviramradai** [lmenezes/cerebro-docker#8]
Is there a way to give -Dplay.ws.ssl.loose.acceptAnyCertificate=true option to the docker?
I am running cerebro on an ssh tunnel and I need ssl verify off.

Thanks

**Comment by rlk5546** [comment]
open a shell in our cerebro container and add `play.ws.ssl.loose.acceptAnyCertificate=true` at the end of your conf/application.conf

**Comment by aviramradai** [comment]
Thanks
I get it.
I thought there is a way to do it without changing the container so I will be able to the updates you do.

**Comment by gillg** [comment]
You can just use `docker run .... -Dplay.ws.ssl.loose.acceptAnyCertificate=true` or in a dockerfile :
```yaml
cerebro:
   container_name: cerebro
   image: ...
   command:
   - -Dplay.ws.ssl.loose.acceptAnyCertificate=true
```
